FirebaseError: Missing or insufficient permissions.
i cannot accept join request , how to solve these isseus once and for all , i want to create the coud functions right , do that then , implement the cloud function for all of these features and lets not always change the rules of the firestore to much